#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process

# Get the PID of the process
pid=$(pgrep -f "4-to_infinity_and_beyond")

if [ -z "$pid" ]
then
  echo "The 4-to_infinity_and_beyond process is not running"
else
  # Kill the process
  kill "$pid"
  #echo "Terminated"
fi
