#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code, and displays this data

log_file="apache-access.log"

awk '{print $1 " " $9}' $log_file | sort | uniq -c | awk '{print $1 " " $2 " " $3}' | sort -nr
