#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes

hour=0

while [ $hour -lt 12 ]
do
    printf "Hour: %d\n" $hour
    minute=1
    while [ $minute -lt 60 ]
    do
        printf "%d\n" $minute
        minute=$((minute+1))
    done
    hour=$((hour+1))
done
